### ISSUE TITLE
Could not open video stream

### ISSUE THREAD

**Issue by cuishao23** [LostXine/naive-scrcpy-client#4]
我的运行后报这个错误，咋解决呢
Found h264 decoder
Could not open video stream
ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:158)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:68)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:28)
        at com.genymobile.scrcpy.Server.main(Server.java:110)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)

**Comment by cuishao23** [comment]
我把"bit_rate": 2 ** 30 降低为2**30  这个问题解决了

**Comment by cuishao23** [comment]
我把"bit_rate": 2 ** 30 降低为2**20 这个问题解决了
