### ISSUE TITLE
OSError: libwebp.so.6 on Ubuntu 22

### ISSUE THREAD

**Issue by babu-s23** [LostXine/naive-scrcpy-client#5]
`Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    [self.run](http://self.run/)()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/XXX/handlers/NaiveScrcpyClient.py", line 105, in _run_decoder
    lib_avcodec = ctypes.CDLL(avcodec_lib)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libwebp.so.6: cannot open shared object file: No such file or directory`

**Comment by Variante** [comment]
Please check whether ffmpeg can run in your environment. If you only need to decode video frames, maybe take a look at this new solution:
https://github.com/LostXine/naive-android-ssr

**Comment by LostXine** [comment]
Please check whether ffmpeg can run in your environment. If you only need to decode video frames, maybe take a look at this new solution:
https://github.com/LostXine/naive-android-ssr

**Comment by babu-s23** [comment]
We are trying to replicate uiautomatorviewer kind of for our tool. For which we need feed from the device.

**Comment by babu-s23** [comment]
I want for image also
